config/routes.rb
Rails.application.routes.draw do
  resources :set_cards do
    resources :flask_cards
  end

  resources :post_comments

  resources :posts 

  resources :hiraganas do
    resources :tests
  end
  devise_for :users
  resources :users
  resources :tests

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homepage#home'
  get 'dict' => 'homepage#dict'
  get 'alphabet' => 'homepage#alphabet'
  get 'news' => 'homepage#news'
  get 'songs' => 'homepage#songs'
  get 'infor' => 'users#show'
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :set_post_comment, only: [:show, :edit, :update, :destroy]

  # GET /post_comments
  # GET /post_comments.json
  def index
    @post_comments = PostComment.all
  end

  # GET /post_comments/1
  # GET /post_comments/1.json
  def show
  end

  # GET /post_comments/new
  def new
    @post_comment = PostComment.new
  end

  # GET /post_comments/1/edit
  def edit
  end

  # POST /post_comments
  # POST /post_comments.json
  def create
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.user_id = current_user.id
    respond_to do |format|
      if @post_comment.save
        url = "/posts/" + @post_comment.post_id.to_s
        format.html { redirect_to url, notice: 'Post comment was successfully created.' }
     
        format.json { render :show, status: :created, location: @post_comment }
      else
        format.html { render :new }
        format.json { render json: @post_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_comments/1
  # PATCH/PUT /post_comments/1.json
  def update
    respond_to do |format|
      if @post_comment.update(post_comment_params)
        format.html { redirect_to @post_comment, notice: 'Post comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_comment }
      else
        format.html { render :edit }
        format.json { render json: @post_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_comments/1
  # DELETE /post_comments/1.json
  def destroy
    @post_comment.destroy
    respond_to do |format|
      format.html { redirect_to post_comments_url, notice: 'Post comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_comment
      @post_comment = PostComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_comment_params
      params.require(:post_comment).permit(:user_id, :post_id, :comment)
    end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_form.html.erb
<%= form_with(model: post_comment, local: true) do |form| %>
  <% if post_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_comment.errors.count, "error") %> prohibited this post_comment from being saved:</h2>

      <ul>
        <% post_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_comments/edit.html.erb
<h1>Editing Post Comment</h1>

<%= render 'form', post_comment: @post_comment %>

<%= link_to 'Show', @post_comment %> |
<%= link_to 'Back', post_comments_path %>

app/views/post_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_comments.each do |post_comment| %>
      <tr>
        <td><%= post_comment.user_id %></td>
        <td><%= post_comment.post_id %></td>
        <td><%= post_comment.comment %></td>
        <td><%= link_to 'Show', post_comment %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(post_comment) %></td>
        <td><%= link_to 'Destroy', post_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Comment', new_post_comment_path %>

app/views/post_comments/new.html.erb
<h1>New Post Comment</h1>

<%= render 'form', post_comment: @post_comment %>

<%= link_to 'Back', post_comments_path %>

app/views/post_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post_comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_comment.post_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post_comment.comment %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@post_comment) %> |
<%= link_to 'Back', post_comments_path %>