config/routes.rb
Rails.application.routes.draw do
  resources :set_cards do
    resources :flask_cards
  end

  resources :post_comments

  resources :posts 

  resources :hiraganas do
    resources :tests
  end
  devise_for :users
  resources :users
  resources :tests

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homepage#home'
  get 'dict' => 'homepage#dict'
  get 'alphabet' => 'homepage#alphabet'
  get 'news' => 'homepage#news'
  get 'songs' => 'homepage#songs'
  get 'infor' => 'users#show'
end

app/models/hiragana.rb
class Hiragana < ApplicationRecord
    has_many :tests, dependent: :destroy
end

app/controllers/hiraganas_controller.rb
class HiraganasController < ApplicationController
  before_action :set_hiragana, only: [:show, :edit, :update, :destroy]

  # GET /hiraganas
  # GET /hiraganas.json
  def index
    @hiraganas = Hiragana.all
  end

  # GET /hiraganas/1
  # GET /hiraganas/1.json
  def show
  end

  # GET /hiraganas/new
  def new
    @hiragana = Hiragana.new
  end

  # GET /hiraganas/1/edit
  def edit
  end

  # POST /hiraganas
  # POST /hiraganas.json
  def create
    @hiragana = Hiragana.new(hiragana_params)

    respond_to do |format|
      if @hiragana.save
        format.html { redirect_to @hiragana, notice: 'Hiragana was successfully created.' }
        format.json { render :show, status: :created, location: @hiragana }
      else
        format.html { render :new }
        format.json { render json: @hiragana.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hiraganas/1
  # PATCH/PUT /hiraganas/1.json
  def update
    respond_to do |format|
      if @hiragana.update(hiragana_params)
        format.html { redirect_to @hiragana, notice: 'Hiragana was successfully updated.' }
        format.json { render :show, status: :ok, location: @hiragana }
      else
        format.html { render :edit }
        format.json { render json: @hiragana.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hiraganas/1
  # DELETE /hiraganas/1.json
  def destroy
    puts "Hello WORLD !!!!!!!!!!!!!!!!!!!"
    @hiragana.destroy
    respond_to do |format|
      format.html { redirect_to hiraganas_url, notice: 'Hiragana was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hiragana
      @hiragana = Hiragana.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hiragana_params
      params.require(:hiragana).permit(:cachviet, :cachdoc)
    end
end

app/helpers/hiraganas_helper.rb
module HiraganasHelper
end

app/views/hiraganas/_card.html.erb
<div class="col-lg-2 card-hira"> 
  <div class="cach_viet">
    <%= hiragana.cachviet %>
  </div>
  <div class="cach_doc">
    <%= hiragana.cachdoc %>
  </div>
  <%# <%= link_to 'tao_test', hiragana %> 
  <%# <%= link_to 'xóa', method: :delete, data: { confirm: 'Are you sure?' } %> 
</div>

app/views/hiraganas/_form.html.erb
<%= form_with(model: hiragana, local: true) do |form| %>
  <% if hiragana.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hiragana.errors.count, "error") %> prohibited this hiragana from being saved:</h2>

      <ul>
        <% hiragana.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cachviet %>
    <%= form.text_field :cachviet %>
  </div>

  <div class="field">
    <%= form.label :cachdoc %>
    <%= form.text_field :cachdoc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hiraganas/edit.html.erb
<h1>Editing Hiragana</h1>

<%= render 'form', hiragana: @hiragana %>

<%= link_to 'Show', @hiragana %> |
<%= link_to 'Back', hiraganas_path %>

app/views/hiraganas/index.html.erb
<p id="notice"><%= notice %></p>
<h2>HIRAGANA</h2>
<%= link_to 'New Hiragana', new_hiragana_path %>
<%= link_to "Test", tests_path %>
<div class="container card_index">
  <div class="row">
    <% @hiraganas.each do |hiragana| %>
      <%= render 'card', hiragana: hiragana  %>
    <% end %>
  </div>
</div>
<p class="back-button"><i class="fas fa-backward"></i><%= link_to "Back", :back %></p>

app/views/hiraganas/new.html.erb
<h1>New Hiragana</h1>

<%= render 'form', hiragana: @hiragana %>

<%= link_to 'Back', hiraganas_path %>

app/views/hiraganas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cachviet:</strong>
  <%= @hiragana.cachviet %>
</p>

<p>
  <strong>Cachdoc:</strong>
  <%= @hiragana.cachdoc %>
</p>

<% @hiragana.tests.each do |t| %>
  <p>
    <strong>Question:</strong>
    <%= t.question %>
  </p>
  <p>
    <span>
      <%= t.answer_a %>
    </span>
    <span>
      <%= t.answer_b %>
    </span>
    <span>
      <%= t.answer_c %>
    </span>
    <span>
      <%= t.answer_d %>
    </span>
  </p>
<% end %>

<%= form_with(model: [ @hiragana, @hiragana.tests.build ], local: true) do |form| %>
  <p>
    <%= form.label :question %><br>
    <%= form.text_field :question %>
  </p>
  <p>
    <%= form.label :answer_a %><br>
    <%= form.text_area :answer_a %>
  </p>
  <p>
    <%= form.label :answer_b %><br>
    <%= form.text_area :answer_b %>
  </p>
  <p>
    <%= form.label :answer_c %><br>
    <%= form.text_area :answer_c %>
  </p>
  <p>
    <%= form.label :answer_d %><br>
    <%= form.text_area :answer_d %>
  </p>
  <p>
    <%= form.label :correct_answer %><br>
    <%= form.text_area :correct_answer %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_hiragana_path(@hiragana) %> |
<%= link_to 'Back', hiraganas_path %>