config/routes.rb
Rails.application.routes.draw do
  resources :set_cards do
    resources :flask_cards
  end

  resources :post_comments

  resources :posts 

  resources :hiraganas do
    resources :tests
  end
  devise_for :users
  resources :users
  resources :tests

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homepage#home'
  get 'dict' => 'homepage#dict'
  get 'alphabet' => 'homepage#alphabet'
  get 'news' => 'homepage#news'
  get 'songs' => 'homepage#songs'
  get 'infor' => 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/flask_card.rb
class FlaskCard < ApplicationRecord
  belongs_to :set_card
end

app/models/hiragana.rb
class Hiragana < ApplicationRecord
    has_many :tests, dependent: :destroy
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :post_comment, -> { order "created_at DESC"}
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
end

app/models/set_card.rb
class SetCard < ApplicationRecord
  belongs_to :user
  has_many :flask_cards, dependent: :destroy
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :hiragana
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :set_cards, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :phone, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_comment = PostComment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :post, :created_at)
    end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
    def index
        @tests = Test.all
    end
    def new
        @test = Test.new
    end
    def create
        @hiragana = Hiragana.find(params[:hiragana_id])
        @test = @hiragana.tests.create(test_params)
        redirect_to hiragana_path(@hiragana)
    end
    def show
        @test = Test.find(params[:id])
        puts @test
    end
    
    private 
        def test_params
            params.require(:test).permit(:question, :answer_a, :answer_b, :answer_c, :answer_d, :correct_answer)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            #Handle a successful save
            flash[:success] = "Welcome to the DHA!"
            redirect_to @user
        else
            render 'new'
        end
    end
    private
        def user_params
            params.require(:user) .permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/flask_cards_helper.rb
module FlaskCardsHelper
end

app/helpers/hiraganas_helper.rb
module HiraganasHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/set_cards_helper.rb
module SetCardsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer d-flex justify-content-around align-items-center">
    <div class="p-2">
        <p><i class="fas fa-copyright"></i> Application made by: Dung, Hiếu, Phương Anh</p>
    </div>

    <div class="p-2">
        <p><i class="fas fa-school"></i> Trường Đại học Bách Khoa Hà Nội</p>
        <p>Viện Công Nghệ Thông Tin Và Truyền Thông</p>
    </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg" >
    <a href="/"><img src="../DHA1.png" alt="icon" style="width: 80px; height: 64px;" ></a>
    <ul class="navbar-nav redirect">
        <li class="nav_ele nav-link"><i class="fas fa-home"></i><%= link_to "Trang chủ", '/' %></li>
        <li class="nav_ele nav-link"><i class="fas fa-language"></i><%= link_to "Từ điển", dict_path %></li>
        
        <li class="dropdown nav_ele nav-item">
        <i class="fas fa-book-reader"></i></i>Bài học
            <div class="dropdown-content">
            <% if user_signed_in? %>
            <%= link_to "Bảng chữ cái", hiraganas_path, class: "dropdown-item" %> </br>
            <%= link_to "Đọc báo",news_path, class: "dropdown-item" %></br>
            <%= link_to "Flask card", set_cards_path, class: "dropdown-item" %></br>
            <% else %>
            <%= link_to "Bảng chữ cái", new_user_session_path, class: "dropdown-item" %> </br>
            <%= link_to "Đọc báo", new_user_session_path , class: "dropdown-item" %></br>
            <%= link_to "Flask card",new_user_session_path, class: "dropdown-item" %></br>
            <% end %>
            </div>
        </li> 
        <li class="nav_ele nav-link"><i class="fas fa-graduation-cap"></i><%= link_to "Phương pháp học", '#' %></li>
        <li class="dropdown nav_ele">
            Phương pháp học
            <div class="dropdown-content">
            <% if user_signed_in? %>
            <%= link_to "Đăng bài",new_post_path, class: "dropdown-item" %> </br>
            <%= link_to "Đọc bài",posts_path, class: "dropdown-item" %></br>
            <% else %>
            <%= link_to "Đăng bài",new_post_path, class: "dropdown-item" %> </br>
            <%= link_to "Đọc bài",posts_path, class: "dropdown-item" %></br>
            <% end %>
        </div>
    </li>
    </ul>

    <ul class="navbar-nav ml-md-auto log-in">
        <% if user_signed_in? %>
        <li class="nav_ele nav-link user_icon"><i class="fas fa-user"></i>
        <%= link_to current_user.name, infor_path  %></li>
        <li style="color: white; margin-top: 12px">|</li>
        <li class="nav_ele nav-link" ><%= link_to "Đăng xuất", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li class="nav_ele nav-link"><%= link_to "Đăng nhập", new_user_session_path %></li>
        <li style="color: white; margin-top: 15px">|</li>
        <li class="form nav_ele nav-link"><%= link_to "Đăng ký", new_user_registration_path %></li>
        <% end %>
    </ul>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to DHA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.3.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css">
  </head>

  <body>
    <div><%= render 'layouts/header' %></div>
    <div class="container-fluid background">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    
  </body>
  
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</html>